table Dim_Product
	lineageTag: dc3d5d2a-3be9-49a5-a375-d9c52393e99e

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: 0e541393-39c8-4d1e-af4a-ed1cd21ad293
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column ProductName
		dataType: string
		lineageTag: 85b2c746-a969-4a22-a459-3b5403a3371c
		summarizeBy: none
		sourceColumn: ProductName

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: c82359c8-a69c-4adc-8d20-a6145e8c24e6
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	partition Dim_Product = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUfJJLCjJLwAyXHNSk0uK8vMyk4uVYnWilYyAYr75pcWpQNoxOTm1uDi/KDMVImcMFHNJLc5WcM5IzCwCctxKi/IyS0qLUpViYwE=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ProductID = _t, ProductName = _t, Category = _t]),
				  #"Changed column type" = Table.TransformColumnTypes(Source, {{"ProductID", Int64.Type}, {"ProductName", type text}, {"Category", type text}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

